openapi: 3.0.0
info:
  title: Skill manager
  version: 1.0.0

paths:
  /{path+}:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: serverless_containers
        container_id: $CONTAINER_ID
        service_account_id: $SA_ID
      parameters:
      - name: path
        in: path
        required: false
        explode: false
        style: simple
        schema:
          type: string
