openapi: 3.0.0

info:
  title: Skill manager
  version: 1.0.0

paths:
  /:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: $FUNC_ID
  /{p1}:
    parameters:
      - $ref: "#/components/parameters/p1"
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: $FUNC_ID
  /admin/{p1}/{p2}:
    parameters:
      - $ref: "#/components/parameters/p1"
      - $ref: "#/components/parameters/p2"
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: $FUNC_ID
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: $FUNC_ID
  /admin/{p1}:
    parameters:
      - $ref: "#/components/parameters/p1"
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: $FUNC_ID
    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: $FUNC_ID

components:
  parameters:
    p1:
      explode: false
      in: path
      name: p1
      required: false
      style: simple
    p2:
      explode: false
      in: path
      name: p2
      required: false
      style: simple
    p3
      explode: false
      in: path
      name: p3
      required: false
      style: simple
