[tool.poetry]
name = "skill-manager"
version = "0.1.0"
description = ""
authors = ["Tim <jlemyp96@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
django = "^3.0.0"
djangorestframework_simplejwt = "^4.3"
django-reversion = "^3.0"
django-filter = "^2.2"
django-extensions = "^2.2"
pyyaml = "^5.1"
uritemplate = "^3.0"
django-loginas = "^0.3.6"
django-cors-headers = "^3.1"
django-constance = {version = "^2.4",extras = ["database"]}
djangorestframework-serializer-extensions = "^2.0.0"
django-autocompletefilter = "^0.0.6"
django-split-settings = "^1.0"
djangorestframework = "^3.10"
django-environ = "^0.4.5"
requests = "^2.22.0"
psycopg2-binary = "^2.8.4"
django-polymorphic = "^2.1.2"
django-markdownx = "^3.0.1"
mdv = "^1.7.4"
django-mptt = "^0.11.0"
django-object-actions = "^2.0.0"

[tool.poetry.dev-dependencies]
Werkzeug = "^1.0"
ipython = "^7.7"
flake8 = "^3.7.9"
isort = "^4.3.21"
flake8-isort = "^2.9.1"
bandit = "^1.6.2"
flake8-bandit = "^2.1.2"
pep8-naming = "^0.9.1"
flake8-variables-names = "^0.0.3"
flake8-bugbear = "^20.1.4"
coverage = {version = "^5.0.3", extras = ["toml"]}
flake8-builtins = "^1.4.2"

[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 3
skip_glob = "**/migrations/*"

[tool.coverage.run]
omit = [ "main/migrations/*" ]
source = [ "." ]

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
