# Generated by Django 3.0.4 on 2020-03-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_skill_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата-время создания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('resources', models.ManyToManyField(blank=True, related_name='notes', to='main.Resource', verbose_name='Ресурсы')),
                ('skills', models.ManyToManyField(blank=True, related_name='notes', to='main.Skill', verbose_name='ЗУНы')),
                ('tag_values', models.ManyToManyField(blank=True, related_name='notes', to='main.TagValue', verbose_name='Метки со значениями')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'default_related_name': 'notes',
            },
        ),
    ]
