# Generated by Django 3.0.4 on 2020-03-11 18:53

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_resource_type_polymorph'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importedresource',
            options={'default_related_name': 'imported_resources', 'verbose_name': 'Импортированный ресурс (git)', 'verbose_name_plural': 'Импортированные ресурсы (git)'},
        ),
        migrations.AddField(
            model_name='importedresourcerepo',
            name='from_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='importedresourcerepo',
            name='homepage',
            field=models.URLField(default='', verbose_name='Домашняя страница'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importedresourcerepo',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='importedresourcerepo',
            name='short_name',
            field=models.CharField(default='', max_length=255, verbose_name='Короткое название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importedresourcerepo',
            name='topics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Топики'),
        ),
        migrations.AddField(
            model_name='importedresourcerepo',
            name='url',
            field=models.URLField(default='', verbose_name='Ссыль на репу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='importedresource',
            name='raw_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Сырые данные'),
        ),
    ]
