# Generated by Django 3.0.4 on 2020-03-13 18:58

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200311_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importedresource',
            options={'default_related_name': 'imported_resources', 'verbose_name': 'Импортированный ресурс', 'verbose_name_plural': 'Импортированные ресурсы'},
        ),
        migrations.AlterModelOptions(
            name='importedresourcerepo',
            options={'default_related_name': 'imported_resources', 'verbose_name': 'Импортированный ресурс (git)', 'verbose_name_plural': 'Импортированные ресурсы (git)'},
        ),
        migrations.AlterModelOptions(
            name='resourcetype',
            options={'default_related_name': 'resource_types', 'verbose_name': 'Тип ресурса', 'verbose_name_plural': 'Типы ресурсов'},
        ),
        migrations.AlterField(
            model_name='importedresourcerepo',
            name='from_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Владелец закладки'),
        ),
        migrations.AlterField(
            model_name='importedresourcerepo',
            name='importedresource_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='imported_resources', serialize=False, to='main.ImportedResource'),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=markdownx.models.MarkdownxField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='comment',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=markdownx.models.MarkdownxField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=markdownx.models.MarkdownxField(verbose_name='Описание'),
        ),
    ]
