# Generated by Django 3.0.4 on 2020-03-22 15:51

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_folder_mptt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='folders',
        ),
        migrations.AddField(
            model_name='skill',
            name='folder',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='main.Folder', verbose_name='Папка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='main.Skill', verbose_name='Батька'),
        ),
    ]
