# Generated by Django 3.0.4 on 2020-03-29 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_task_mptt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='main.Folder', verbose_name='Папка'),
        ),
    ]
