# Generated by Django 3.0.4 on 2020-04-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200329_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='folder',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
