# Generated by Django 3.1.5 on 2021-01-31 10:45

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rm_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedresourcerepo',
            name='readme',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='README'),
        ),
        migrations.AlterField(
            model_name='importedresource',
            name='raw_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Сырые данные'),
        ),
    ]
