version: "3"

services:
  backend:
    image: skill-manager
    build:
      context: .
    environment:
      PORT: ${PORT:-8000}
      DEBUG: true
      DATABASE_URL: ${DATABASE_URL?}
    ports:
      - "8000:8000"
    command: python manage.py runserver_plus 0.0.0.0:${PORT:-8000}
