version: "3"

services:
  backend:
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-pipeline-stages: |
          - json:
              expressions:
                event: event
                timestamp: timestamp
                request_id: request_id
                logger: logger
                level: level
                method: method
                code: code
                path: path
                exception: exception
          - labels:
              logger:
              level:
              method:
              code:
              path:
