version: "3"

services:
  backend:
    image: skill-manager
    restart: unless-stopped
    networks:
      - default
    environment:
      PORT: ${PORT:-8000}
      DEBUG: ${DEBUG:-false}
      DATABASE_URL: ${DATABASE_URL?}
    logging:
      driver: json-file
      options:
        max-size: 50m
