version: "3"

services:
  backend:
    networks:
      - proxy
    labels:
      reproxy.server: '*'
      reproxy.port: ${PORT:-8000}
      # reptoxy.route: /
      reproxy.route: '^/(.*)'
      # reproxy.dst: /
      # reproxy.dst: '/$$1'
      reproxy.ping: '/ht/'

networks:
  proxy:
    external: true
