version: "3"

services:
  tempo-query:
    image: grafana/tempo-query
    environment:
    - BACKEND=tempo:80
    ports:
    - "16686:16686"  # jaeger-ui
    depends_on:
    - tempo
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
