# Generated by Django 2.2.6 on 2019-11-20 13:32

from django.db import migrations, models
import django.db.models.deletion
import utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата-время создания')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('order_num', models.PositiveIntegerField(default=0, verbose_name='Очередь')),
                ('like', models.BooleanField(default=False, verbose_name='Лайк')),
                ('icon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
                'default_related_name': 'folders',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата-время создания')),
                ('points', models.FloatField(verbose_name='Очки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Прогресс',
                'verbose_name_plural': 'Прогресс',
                'default_related_name': 'progress',
            },
        ),
        migrations.CreateModel(
            name='Remind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата-время создания')),
                ('datetime', models.DateTimeField(verbose_name='Дата-время срабатывания')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включено')),
                ('interval', models.DurationField(verbose_name='Интервал повторения')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'default_related_name': 'reminds',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата-время создания')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('order_num', models.PositiveIntegerField(default=0, verbose_name='Очередь')),
                ('like', models.BooleanField(default=False, verbose_name='Лайк')),
                ('icon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Иконка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='Объем')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссыль')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текс')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('planned_progress_points', models.FloatField(default=0, verbose_name='Планируемые очки прогресса')),
                ('difficulty_points', models.FloatField(default=0, verbose_name='Очки сложности')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
                'default_related_name': 'resources',
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('order_num', models.PositiveIntegerField(default=0, verbose_name='Очередь')),
            ],
            options={
                'verbose_name': 'Тип ресурса',
                'verbose_name_plural': 'Типы ресурсы',
                'default_related_name': 'resource_types',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата-время создания')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('order_num', models.PositiveIntegerField(default=0, verbose_name='Очередь')),
                ('like', models.BooleanField(default=False, verbose_name='Лайк')),
                ('icon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Иконка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('planned_progress_points', models.FloatField(default=0, verbose_name='Планируемые очки прогресса')),
                ('difficulty_points', models.FloatField(default=0, verbose_name='Очки сложности')),
            ],
            options={
                'verbose_name': 'ЗУН',
                'verbose_name_plural': 'ЗУНы',
                'default_related_name': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата-время создания')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('order_num', models.PositiveIntegerField(default=0, verbose_name='Очередь')),
                ('like', models.BooleanField(default=False, verbose_name='Лайк')),
                ('icon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Иконка')),
                ('color', utils.fields.ColorField(verbose_name='Цвет')),
                ('target_type', models.PositiveIntegerField(default=7, verbose_name='Тип цели')),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
                'default_related_name': 'tags',
            },
        ),
        migrations.CreateModel(
            name='TagValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата-время создания')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('order_num', models.PositiveIntegerField(default=0, verbose_name='Очередь')),
                ('icon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Значение метки',
                'verbose_name_plural': 'Значения меток',
                'default_related_name': 'values',
            },
        ),
        migrations.CreateModel(
            name='VolumeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата-время создания')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('order_num', models.PositiveIntegerField(default=0, verbose_name='Очередь')),
            ],
            options={
                'verbose_name': 'Тип объема',
                'verbose_name_plural': 'Типы объема',
                'default_related_name': 'volume_types',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата-время создания')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('order_num', models.PositiveIntegerField(default=0, verbose_name='Очередь')),
                ('like', models.BooleanField(default=False, verbose_name='Лайк')),
                ('description', models.TextField(verbose_name='Описание')),
                ('planned_progress_points', models.FloatField(default=0, verbose_name='Планируемые очки прогресса')),
                ('difficulty_points', models.FloatField(default=0, verbose_name='Очки сложности')),
                ('competed', models.BooleanField(default=False, verbose_name='Завершена')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='main.Task', verbose_name='Батя')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'default_related_name': 'tasks',
            },
        ),
    ]
