# Generated by Django 2.2.6 on 2019-11-20 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.Project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='task',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='main.Resource', verbose_name='Ресурсы'),
        ),
        migrations.AddField(
            model_name='task',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main.Skill', verbose_name='ЗУН'),
        ),
        migrations.AddField(
            model_name='task',
            name='tag_values',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='main.TagValue', verbose_name='Метки со значениями'),
        ),
        migrations.AddField(
            model_name='tagvalue',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='main.Tag', verbose_name='Метка'),
        ),
        migrations.AddField(
            model_name='skill',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='skills', to='main.Folder', verbose_name='Папки'),
        ),
        migrations.AddField(
            model_name='skill',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='skills', to='main.Resource', verbose_name='Ресурсы'),
        ),
        migrations.AddField(
            model_name='skill',
            name='tag_values',
            field=models.ManyToManyField(blank=True, related_name='skills', to='main.TagValue', verbose_name='Метки со значениями'),
        ),
        migrations.AddField(
            model_name='resource',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='main.Resource', verbose_name='Батя'),
        ),
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='main.ResourceType', verbose_name='Тип ресурса'),
        ),
        migrations.AddField(
            model_name='resource',
            name='volume_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='main.VolumeType', verbose_name='Тип объема'),
        ),
        migrations.AddField(
            model_name='remind',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminds', to='main.Resource', verbose_name='Ресурс'),
        ),
        migrations.AddField(
            model_name='remind',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminds', to='main.Skill', verbose_name='ЗУН'),
        ),
        migrations.AddField(
            model_name='remind',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminds', to='main.Task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='progress',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='main.Resource', verbose_name='Ресурс'),
        ),
        migrations.AddField(
            model_name='progress',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='main.Task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders', to='main.Folder', verbose_name='Батя'),
        ),
    ]
