# Generated by Django 2.2.6 on 2019-11-20 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата-время создания')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('order_num', models.PositiveIntegerField(default=0, verbose_name='Очередь')),
                ('like', models.BooleanField(default=False, verbose_name='Лайк')),
                ('icon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Иконка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('resources', models.ManyToManyField(blank=True, related_name='project', to='main.Resource', verbose_name='Ресурсы')),
                ('skills', models.ManyToManyField(blank=True, related_name='project', to='main.Skill', verbose_name='ЗУНы')),
                ('tag_values', models.ManyToManyField(blank=True, related_name='project', to='main.TagValue', verbose_name='Метки со значениями')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'default_related_name': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата-время создания')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('order_num', models.PositiveIntegerField(default=0, verbose_name='Очередь')),
                ('like', models.BooleanField(default=False, verbose_name='Лайк')),
                ('description', models.TextField(verbose_name='Описание')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_variants', to='project.Project', verbose_name='Проект')),
                ('resources', models.ManyToManyField(blank=True, related_name='project_variants', to='main.Resource', verbose_name='Ресурсы')),
                ('skills', models.ManyToManyField(blank=True, related_name='project_variants', to='main.Skill', verbose_name='ЗУНы')),
                ('tag_values', models.ManyToManyField(blank=True, related_name='project_variants', to='main.TagValue', verbose_name='Метки со значениями')),
            ],
            options={
                'verbose_name': 'Вариант проекта',
                'verbose_name_plural': 'Варианты проектов',
                'default_related_name': 'project_variants',
            },
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссыль')),
                ('project_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='project.ProjectVariant', verbose_name='Вариант проекта')),
            ],
            options={
                'verbose_name': 'Ссылка на проект',
                'verbose_name_plural': 'Ссылки на проект',
                'default_related_name': 'project_links',
            },
        ),
    ]
