# Generated by Django 3.0.3 on 2020-02-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='projectvariant',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
    ]
