# Generated by Django 3.0.4 on 2020-03-13 18:58

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200216_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=markdownx.models.MarkdownxField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='projectvariant',
            name='description',
            field=markdownx.models.MarkdownxField(verbose_name='Описание'),
        ),
    ]
