# Generated by Django 2.2.6 on 2019-11-20 17:05

from django.db import migrations
import apps.main.models.tag
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191120_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='target_type',
            field=utils.fields.IntFlagField(default=apps.main.models.tag.Tag.TARGET_TYPE(7), enum=['FOLDER', 'RESOURCE', 'SKILL'], verbose_name='Тип цели'),
        ),
    ]
