# Generated by Django 3.0.3 on 2020-02-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_resourcetype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='raw_data',
            field=models.TextField(blank=True, null=True, verbose_name='Сырые данные'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
