# Generated by Django 3.0.3 on 2020-02-16 19:01

from django.db import migrations
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_resource_tag_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=utils.fields.ColorField(blank=True, null=True, verbose_name='Цвет'),
        ),
    ]
