# Generated by Django 3.0.3 on 2020-02-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200216_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='simple',
            field=models.BooleanField(default=True, verbose_name='Простая (без значений)'),
        ),
    ]
