name: lint

on: [push]

jobs:
  src:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "poetry>=1.0.0"
        poetry config virtualenvs.create false
        poetry install
    - run: flakehell lint src --count --exit-zero
