name: release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  image:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v2
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: docker/Dockerfile.prod
          registry: ghcr.io
          name: ${{ github.repository }}
          tag_names: true
          cache: true
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: docker/Dockerfile.prod.alpine
          registry: ghcr.io
          name: ${{ github.repository }}
          tags: "${GITHUB_HEAD_REF}-alpine"
          cache: true
